import { useRef } from 'react';
import { Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { isFeatureAvailable } from '@/lib/tierConfig';
import { Link } from 'react-router-dom';

/**
 * Wraps content in a print-ready layout.
 * - Renders a "Print / Save PDF" button when tier allows it
 * - On print: hides sidebar, header, and all elements with class `no-print`
 * - Shows org name, report title, generated date in print header
 */
export default function PrintReportWrapper({ orgName, reportTitle, tier, children }) {
  const canPrint = isFeatureAvailable(tier || 'free', 'pdf_reports');
  const ref = useRef(null);

  const handlePrint = () => {
    const el = ref.current;
    if (!el) return;
    el.classList.add('printing');
    window.print();
    el.classList.remove('printing');
  };

  return (
    <div ref={ref} className="print-report-root">
      {/* Print-only header */}
      <div className="hidden print:block mb-6 pb-4 border-b border-gray-300">
        <p className="text-xs text-gray-500 uppercase tracking-widest mb-1">Skills Matrix App</p>
        <h1 className="text-2xl font-bold text-gray-900">{reportTitle}</h1>
        {orgName && <p className="text-sm text-gray-600 mt-1">{orgName}</p>}
        <p className="text-xs text-gray-400 mt-1">Generated {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
      </div>

      {/* Print button — screen only */}
      <div className="no-print flex justify-end mb-4">
        {canPrint ? (
          <Button variant="outline" size="sm" onClick={handlePrint} className="gap-1.5">
            <Printer className="w-3.5 h-3.5" /> Print / Save PDF
          </Button>
        ) : (
          <Button variant="outline" size="sm" asChild className="gap-1.5 opacity-60">
            <Link to="/settings?tab=billing" title="Available on Professional plan">
              <Printer className="w-3.5 h-3.5" /> Print — Professional only
            </Link>
          </Button>
        )}
      </div>

      {children}

      {/* Print-only footer */}
      <div className="hidden print:block mt-8 pt-4 border-t border-gray-200 text-xs text-gray-400 flex justify-between">
        <span>Generated by Skills Matrix App</span>
        <span>{new Date().toLocaleDateString('en-GB')}</span>
      </div>

      <style>{`
        @media print {
          /* Hide everything outside the print root */
          body > *:not(.print-report-root),
          nav, aside, header,
          [data-sidebar], [data-nav],
          .no-print {
            display: none !important;
          }
          .print-report-root {
            position: static !important;
            margin: 0 !important;
            padding: 24px !important;
            max-width: 100% !important;
          }
          /* Clean up card borders */
          .bg-card, .border {
            box-shadow: none !important;
          }
          /* Ensure table rows don't split across pages */
          tr { page-break-inside: avoid; }
          h2, h3 { page-break-after: avoid; }
        }
      `}</style>
    </div>
  );
}
